title: Blog Técnico CorelTech
description: Artículos sobre tecnología, redes y mantenimiento de equipos.
baseurl: ""
url: "https://tu-sitio.netlify.app "
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  - name: blog
    output: true
    permalink: /blog/:year/:month/:day/:slug/
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Autor", name: "author", widget: "string", default: "Equipo CorelTech"}
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Imagen destacada", name: "image", widget: "image", media_folder: "static/img/blog", public_folder: "/img/blog"}
      - {label: "Categoría", name: "category", widget: "select", options: ["Redes", "Hardware", "Software"]}
      - {label: "Contenido", name: "body", widget: "markdown"}